# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=2048)),
                ('tmp', models.IntegerField()),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='URL', max_length=2048)),
                ('founddatetime', models.DateTimeField(db_column='FoundDateTime')),
                ('lastscandate', models.DateTimeField(db_column='LastScanDate', null=True)),
                ('tmp', models.IntegerField()),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_column='Rank')),
                ('tmp', models.IntegerField()),
                ('pageid', models.ForeignKey(db_column='PageID', on_delete=django.db.models.deletion.CASCADE, to='main_app.Pages')),
            ],
            options={
                'db_table': 'personpagerank',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=2048, unique=True)),
                ('isactive', models.BooleanField(db_column='Active', default=True)),
                ('tmp', models.IntegerField()),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=2048, unique=True)),
                ('url', models.CharField(db_column='URL', max_length=2048)),
                ('isactive', models.BooleanField(db_column='Active', default=True)),
                ('tmp', models.IntegerField()),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login', models.TextField(db_column='Login', unique=True)),
                ('isadmin', models.BooleanField(db_column='Admin', default=False)),
                ('password', models.TextField(db_column='Password')),
                ('isactive', models.BooleanField(db_column='Active', default=True)),
                ('tmp', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='sites',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='main_app.Users'),
        ),
        migrations.AddField(
            model_name='persons',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='main_app.Users'),
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='personid',
            field=models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='main_app.Persons'),
        ),
        migrations.AddField(
            model_name='pages',
            name='siteid',
            field=models.ForeignKey(db_column='SiteID', on_delete=django.db.models.deletion.CASCADE, to='main_app.Sites'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='personid',
            field=models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='main_app.Persons'),
        ),
        migrations.AlterUniqueTogether(
            name='sites',
            unique_together=set([('name', 'userid')]),
        ),
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together=set([('name', 'userid')]),
        ),
        migrations.AlterUniqueTogether(
            name='personpagerank',
            unique_together=set([('personid', 'pageid')]),
        ),
    ]
