# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='tmp',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='tmp',
        ),
        migrations.RemoveField(
            model_name='personpagerank',
            name='tmp',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='tmp',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='tmp',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tmp',
        ),
    ]
